openapi: 3.0.3
info:
  title: Plataforma de Gestión de Tareas - NUEVO SPA
  description: API RESTful para la gestión de usuarios y tareas con autenticación JWT.
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /auth/login:
    post:
      summary: Autenticar usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Autenticación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtResponse'
        '401':
          description: Credenciales inválidas

  /tareas:
    get:
      summary: Obtener todas las tareas
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de tareas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

    post:
      summary: Crear nueva tarea
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Tarea creada

  /tareas/{id}:
    get:
      summary: Obtener tarea por ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Tarea encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tarea no encontrada

    put:
      summary: Actualizar tarea
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Tarea actualizada

    delete:
      summary: Eliminar tarea
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Tarea eliminada

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: admin
        password:
          type: string
          format: password
          example: admin123

    JwtResponse:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI...

    User:
      type: object
      required:
        - id
        - username
        - password
      properties:
        id:
          type: integer
          format: int64
          example: 1
        username:
          type: string
          example: admin
        password:
          type: string
          format: password
          example: admin123

    TaskStatus:
      type: object
      required:
        - id
        - nombre
      properties:
        id:
          type: integer
          format: int64
          example: 1
        nombre:
          type: string
          example: Pendiente

    Task:
      type: object
      required:
        - id
        - titulo
        - descripcion
        - estado
        - usuarioId
      properties:
        id:
          type: integer
          format: int64
          example: 1
        titulo:
          type: string
          example: Implementar login
        descripcion:
          type: string
          example: Agregar autenticación con JWT
        estado:
          $ref: '#/components/schemas/TaskStatus'
        userId:
          type: integer
          format: int64
          example: 1


